/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userController = require('./user.controller');
module.exports.testController = require('./test.controller');
