/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userService = require('./user.service');
module.exports.testService = require('./test.service');
module.exports.authService = require('./auth.service');
module.exports.emailService = require('./email.service');
module.exports.tokenService = require('./token.service');
module.exports.passportService = require('./passport.service');
module.exports.s3Service = require('./s3.service');
module.exports.temps3CronService = require('./temps3Cron.service');
module.exports.notificationService = require('./notification.service');
module.exports.stripeService = require('./stripe.service');
module.exports.queueService = require('./queue.service');
